# Chapter02 Numpy数组基础
## 2.1 Numpy数组属性
- 构建随机数生成器 `rng = np.random.default_rng(seed=:number)`
- 利用生成器生成随机数
    - 生成整数：`rng.integers(low::number,high::number,size=(x::int,y::int...))`
- Numpy数组属性
    - 维度 `.ndim`
    - 形状 `.shape`
    - 尺寸 `.size`
    - 数据类型 `.dtype`

In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)

x1 = rng.integers(10, size=6)
x2 = rng.integers(10, size=(3, 4))
x3 = rng.integers(10, size=(3, 4, 5))

print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("dtype: ", x3.dtype)


x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:  int64


## 2.2 数组索引
- 从 `0` 开始
- 从后往前索引 `-n`
- 可直接用 `=` 修改 `ndarray` 中的某个元素
    - **注** 由于 `ndarray` 仅有一种数据类型，Python会将修改的数据转化为 `ndarray` 原来的数据类型

In [2]:
x1


array([9, 4, 0, 3, 8, 6])

In [3]:
x1[0]


9

In [4]:
x1[4]


8

In [5]:
x1[-1]


6

In [6]:
x2


array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [7]:
x2[2, -1]


9

In [8]:
x1[0] = 3.14159
x1


array([3, 4, 0, 3, 8, 6])

## 2.3 数组剪切
### 2.3.1 一维数组剪切
- 截取`x1`的前 $t$ 个元素 `x1[:t]`
- 截取`x1`的第 $s$ 之后的所有元素 `x1[s:]`
- 截取`x1`的第 $s+1$ 到第 $t$ 个元素 `x1[s:t]`
- 从第 $s+1$ 个开始，每隔 $p-1$ 个元素截取一个元素组成新数组 `x1[s::t]`
    - $t<0$ 时，反向取，特别地`x1[::-1]`将`x1`顺序颠倒

In [9]:
x1[:3]


array([3, 4, 0])

In [10]:
x1[3:]


array([3, 8, 6])

In [11]:
x1[1:4]


array([4, 0, 3])

In [12]:
x1[::2]


array([3, 0, 8])

In [13]:
x1[1::2]


array([4, 3, 6])

In [14]:
x1[::-1]


array([6, 8, 3, 0, 4, 3])

In [15]:
x1[4::-2]


array([8, 0, 3])

### 2.3.2 多维数组剪切

In [16]:
x2


array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [17]:
x2[:2, :3]


array([[3, 1, 3],
       [4, 0, 2]])

In [18]:
x2[:3, ::2]


array([[3, 3],
       [4, 2],
       [0, 6]])

In [19]:
x2[::-1, ::-1]


array([[9, 6, 0, 0],
       [3, 2, 0, 4],
       [7, 3, 1, 3]])

## 2.3.3 数组剪切与数组复制
- `ndarray`默认不复制，故在将`ndarray`的片段赋给一个新变量后，若修改这个新变量内的元素，会修改原 `ndarray`的对应元素
- 若不希望修改原数组，则采用`.copy()`的方法

In [20]:
print("x2:\n", x2)

x2_sub = x2[:2, :2]
print("\nx2_sub:\n", x2_sub)

x2_sub[0, 0] = 99
print("\nx2_sub modified: \n", x2_sub)

print("\nx2: \n", x2)


x2:
 [[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]

x2_sub:
 [[3 1]
 [4 0]]

x2_sub modified: 
 [[99  1]
 [ 4  0]]

x2: 
 [[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [21]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

x2_sub_copy[0, 0] = 42
print("\nx2_sub_copy modified: \n", x2_sub_copy)

print("\nx2: \n", x2)


[[99  1]
 [ 4  0]]

x2_sub_copy modified: 
 [[42  1]
 [ 4  0]]

x2: 
 [[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


## 2.3 重塑矩阵形状
- 方法：`.reshape((x::int,y::int,...))` 
- `np.newaxis` 矩阵升维，**但仅能升一个维度**

In [22]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
x = np.array([1, 2, 3])
x.reshape((1, 3))


array([[1, 2, 3]])

In [24]:
x.reshape((3, 1))


array([[1],
       [2],
       [3]])

In [25]:
x[np.newaxis, :]


array([[1, 2, 3]])

In [26]:
x[:, np.newaxis]


array([[1],
       [2],
       [3]])

In [27]:
x = np.arange(1, 10).reshape(3, 3)
nx = x[:, np.newaxis, :].copy()
print(nx)


[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [28]:
nx[1, 0, 2]


6

## 2.4 数组拼接与拆分
### 2.4.1 数组拼接
- 维度相同时 `np.concatenate([x::ndarray,y::ndarray,...],axis=n::int)`
- 维度不同时 
    - `np.vstack([x::ndarray,y::ndarray,...])` 
    - `np.hstack([x::ndarray,y::ndarray,...])`

In [29]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])


array([1, 2, 3, 3, 2, 1])

In [30]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))


[ 1  2  3  3  2  1 99 99 99]


In [31]:
grid = np.arange(1, 7).reshape(2, 3)
np.concatenate([grid, grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [32]:
np.concatenate([grid, grid], axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [33]:
np.vstack([x, grid])


array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
y = np.array([99, 99])[:, np.newaxis]
np.hstack([grid, y])


array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

### 2.4.2 数组拆分
- 从 $i1,\ i2,\cdots$ 切分数组：`np.split(x::ndarray, [i1::int, i2::int, ...])`
- `np.vsplit`
- `np.hsplit`

In [35]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)


[1 2 3] [99 99] [3 2 1]


In [36]:
grid = np.arange(16).reshape((4, 4))
grid


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
upper, lower = np.vsplit(grid, [2])
print(upper, "\n\n", lower)


[[0 1 2 3]
 [4 5 6 7]] 

 [[ 8  9 10 11]
 [12 13 14 15]]


In [38]:
left, right = np.hsplit(grid, [2])
print(left, "\n\n", right)


[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
