# Chapter01 Python的数据类型
- Python Interger和Python List不仅仅是Integer和List；相较于C和Java这种静态语言，Python动态语言具有易于上手的特点，但其的数据类型往往不像静态语言那么简单，导致运行时往往会比较耗时。
- Python的固定类型Array（更高效，但在科学计算中无用）

In [1]:
import array
L = list(range(10))
A = array.array('i', L)
print(A)


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## 1.1 构建 `ndarray`
1. 直接由 `list` 构建
    - `np.array(:list, dtype=:datatype)`
    - **注** 不同于 `list`，`ndarray` 中有且仅有一种数据类型

In [2]:
import numpy as np
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [3]:
np.array([3.14, 4, 2, 3])


array([3.14, 4.  , 2.  , 3.  ])

In [4]:
np.array([1, 2, 3, 4], dtype=np.float32)


array([1., 2., 3., 4.], dtype=float32)

In [5]:
np.array([range(i, i+3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

2. 从零构建新数组
    - 构建 $x$ 行 $y$ 列**零数组**：`np.zeros((x::int,y::int), dtype=:datatyle)`
    - 构建 $x$ 行 $y$ **由 $z$ 组成的数组**：`np.full((x::int,y::int), z::number)`
    - 构建以 $s$ 为起点，$t$ 为终点，步长为 $p$ 的数组：`np.arange(s::number, t::number, p::number)`
    - 构建横跨 $s, t$ 的 $n$ 个数组成的数组：`np.linspace(s::number, t::number, n::number)`
    - 构建 $x$ 行 $y$ 列，由 $[0,1]$ 间**均匀分布**随机数组成的矩阵：`np.random.random((x::int,y::int))`
    - 构建 $x$ 行 $y$ 列，由 $\mu$ 为期望，$\sigma$ 为方差的正态分布随机数组成的矩阵：`np.random.normal(mu::number, sigma::number, (x::int, y::int))`
    - 构建 $x$ 行 $y$ 列，由 $[s, t)$ 间的随机整数组成的矩阵：`np.random.randint(s::number, t::number, (x::int, y::int))`
    - 构建 $n\times n$ 的单位矩阵：`np.eye(n::int)`
    - 构建 $x$ 行 $y$ 列的空数组：`np.empty((x::int,y::int))`


In [6]:
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.zeros((3, 5), dtype=float)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.full((3, 5), 3.14)


array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.full((3, 5), 3.14, dtype=int)


array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [10]:
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.random((3, 3))


array([[0.81029384, 0.01706397, 0.91590004],
       [0.01400635, 0.0095625 , 0.12568283],
       [0.11684889, 0.0598835 , 0.47976013]])

In [13]:
np.random.normal(0, 1, (3, 3))


array([[ 0.01837333,  0.73090063, -0.06910099],
       [ 0.98119357, -1.31636659,  1.08917764],
       [-1.10587791,  0.70858925, -0.36943092]])

In [14]:
np.random.randint(0, 10, (3, 3))


array([[5, 9, 0],
       [0, 2, 8],
       [1, 1, 4]])

In [15]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.empty(3)


array([1., 1., 1.])